import { createClient, type SupabaseClient } from '@supabase/supabase-js';

const supabaseUrl = (import.meta as any).env?.VITE_SUPABASE_URL;
const supabaseAnonKey = (import.meta as any).env?.VITE_SUPABASE_ANON_KEY;

export const isSupabaseConfigured = Boolean(
  supabaseUrl &&
    supabaseAnonKey &&
    typeof supabaseUrl === 'string' &&
    typeof supabaseAnonKey === 'string' &&
    supabaseUrl.trim().length > 0 &&
    supabaseAnonKey.trim().length > 0
);

export const supabase: SupabaseClient | null = isSupabaseConfigured
  ? createClient(supabaseUrl, supabaseAnonKey)
  : null;

/**
 * SQL Schema for Supabase:
 * Execute this in your Supabase SQL Editor:
 *
 * CREATE TABLE IF NOT EXISTS events (
 *   id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 *   chain_id BIGINT DEFAULT 43113,
 *   onchain_id BIGINT,
 *   title TEXT NOT NULL,
 *   description TEXT,
 *   organizer TEXT,
 *   organizer_address TEXT,
 *   organizer_initials TEXT DEFAULT 'SP',
 *   date TEXT,
 *   location TEXT,
 *   price TEXT DEFAULT '0.1 AVAX',
 *   deposit_numeric NUMERIC DEFAULT 0.1,
 *   capacity INT DEFAULT 100,
 *   sold INT DEFAULT 0,
 *   category TEXT DEFAULT 'Tech',
 *   image TEXT,
 *   gradient TEXT,
 *   created_at TIMESTAMPTZ DEFAULT NOW()
 * );
 *
 * CREATE TABLE IF NOT EXISTS tickets (
 *   id TEXT PRIMARY KEY,
 *   event_id BIGINT,
 *   attendee_address TEXT NOT NULL,
 *   deposit_amount TEXT NOT NULL,
 *   status TEXT DEFAULT 'staked',
 *   tx_hash TEXT,
 *   checked_in_at TIMESTAMPTZ,
 *   created_at TIMESTAMPTZ DEFAULT NOW()
 * );
 */
